# ~/.local/share/gnupg/gpg.conf
# NOTE: this ALHP build of gnupg reads config from the HOMEDIR, not from
# $XDG_CONFIG_HOME/gnupg. Homedir = ~/.local/share/gnupg (XDG_DATA_HOME).

keyid-format long
digest-algo SHA256
cert-digest-algo SHA256

default-key C1A29A75A02E1E74464CA02EA01C523925C94DB0
default-recipient-self