[Application]
locale=en_US

[Backup]
location=/home/alessio/.local/share/ghostwriter/backups/

[FileHistory]
1\cursorPosition=2489
1\filePath=/home/alessio/.local/share/dotfiles/INSTALL.md
2\cursorPosition=57
2\filePath=/home/alessio/Documents/last-will/README.md
size=2

[FindReplace]
highlightMatches=false
matchCase=false
regularExpression=false
wholeWord=false

[LastOpenedFile]
cursorPosition=0
filePath=/home/alessio/code/four-in-a-row/docs/rl-theory.md
folderPath=/home/alessio/code/four-in-a-row/docs

[Preview]
codeFont="Sans Serif,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,,0,0"
htmlPreviewOpen=true
lastUsedExporter=cmark-gfm
lastUsedExporterParams=
textFont="Noto Serif,12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,,0,0"

[Save]
autoSave=true
backupFile=true

[Session]
favoriteStatistic=0
rememberFileHistory=true
restoreSession=true

[Sidebar]
rememberFolderViewShowAllFiles=false

[Spelling]
liveSpellCheck=true

[Style]
blockquoteStyle=false
darkModeEnabled=true
displayTimeInFullScreen=true
editorFont="Sans Serif,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,,0,0"
editorWidth=1
focusMode=1
hideMenuBarInFullScreenEnabled=true
interfaceStyle=0
largeHeadings=true
theme=Nord
underlineInsteadOfItalics=false

[Tabs]
insertSpacesForTabs=false
tabWidth=4

[Typing]
autoMatchEnabled=true
autoMatchFilter=\"'([{*_`<
bulletPointCyclingEnabled=true

[Window]
mainWindowGeometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\v\x1f\0\0\x6\a\0\0\0\0\0\0\0\0\0\0\v\x1f\0\0\x6\a\0\0\0\x1\0\0\0\0\v@\0\0\0\0\0\0\0\0\0\0\v\x1f\0\0\x6\a)
mainWindowState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\v \0\0\x5\xcc\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\0)
sidebarOpen=true
splitterGeometry=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x3\0\0\x1 \0\0\x4\xa6\0\0\x4\x9a\0\xff\xff\xff\xff\x1\0\0\0\x1\0)

[style]
showUnbreakableSpace=false
